name: employees-api-prod
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: employees-api-prod_sqlserver
    restart: always
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA="Y"
      - SA_PASSWORD=$DB_PASSWORD
    networks:
      - localnet

  backend:
    depends_on:
      - sqlserver
    container_name: employees-api-prod_backend
    build:
      context: ./
      dockerfile: ./prod.Dockerfile
      args:
        - DATABASE_URL
    ports:
      - "3000:3000"
    networks:
      - localnet

networks:
  localnet:
    driver: bridge
