-- Generated by the command: npx prisma migrate diff --from-empty --to-schema-datasource prisma/schema.prisma --script

BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[Departamento] (
    [id] INT NOT NULL IDENTITY(1,1),
    [nombre] NVARCHAR(1000) NOT NULL,
    [descripcion] NVARCHAR(1000),
    [activo] BIT NOT NULL CONSTRAINT [Departamento_activo_df] DEFAULT 1,
    CONSTRAINT [Departamento_pkey] PRIMARY KEY CLUSTERED ([id] ASC)
);

-- CreateTable
CREATE TABLE [dbo].[Empleado] (
    [id] INT NOT NULL IDENTITY(1,1),
    [personaId] INT NOT NULL,
    [activo] BIT NOT NULL CONSTRAINT [Empleado_activo_df] DEFAULT 1,
    [departamentoId] INT NOT NULL,
    CONSTRAINT [Empleado_pkey] PRIMARY KEY CLUSTERED ([id] ASC),
    CONSTRAINT [Empleado_personaId_key] UNIQUE NONCLUSTERED ([personaId] ASC)
);

-- CreateTable
CREATE TABLE [dbo].[Persona] (
    [id] INT NOT NULL IDENTITY(1,1),
    [nombre] NVARCHAR(1000) NOT NULL,
    [apellidoPaterno] NVARCHAR(1000) NOT NULL,
    [apellidoMaterno] NVARCHAR(1000) NOT NULL,
    [fechaNacimiento] DATE NOT NULL,
    [direccion] NVARCHAR(1000),
    [telefono] NVARCHAR(1000),
    CONSTRAINT [Persona_pkey] PRIMARY KEY CLUSTERED ([id] ASC)
);

-- CreateTable
CREATE TABLE [dbo].[User] (
    [id] INT NOT NULL IDENTITY(1,1),
    [email] NVARCHAR(1000) NOT NULL,
    [name] NVARCHAR(1000),
    [password] NVARCHAR(1000) NOT NULL,
    CONSTRAINT [User_pkey] PRIMARY KEY CLUSTERED ([id] ASC),
    CONSTRAINT [User_email_key] UNIQUE NONCLUSTERED ([email] ASC)
);

-- AddForeignKey
ALTER TABLE [dbo].[Empleado] ADD CONSTRAINT [Empleado_departamentoId_fkey] FOREIGN KEY ([departamentoId]) REFERENCES [dbo].[Departamento]([id]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[Empleado] ADD CONSTRAINT [Empleado_personaId_fkey] FOREIGN KEY ([personaId]) REFERENCES [dbo].[Persona]([id]) ON DELETE CASCADE ON UPDATE CASCADE;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH

